//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddOnSub
    {
        public int add_id { get; set; }
        public Nullable<int> shareid { get; set; }
        public Nullable<int> subid { get; set; }
        public Nullable<int> No_of_share { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> authorizer { get; set; }
        public Nullable<System.DateTime> authorizationdate { get; set; }
    
        public virtual Shareholder Shareholder { get; set; }
        public virtual Subscribtion Subscribtion { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
