//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int LogID { get; set; }
        public string Message { get; set; }
        public string ActionType { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> PerformedBy { get; set; }
        public string PerformerBranch { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
