//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blocked
    {
        public int BlockID { get; set; }
        public Nullable<int> ShID { get; set; }
        public Nullable<int> PayID { get; set; }
        public Nullable<decimal> BlockedAmount { get; set; }
        public string BlockingOrgan { get; set; }
        public Nullable<int> BlockedBy { get; set; }
        public Nullable<System.DateTime> DateBlocked { get; set; }
        public Nullable<int> BlockingDoc { get; set; }
        public string RefNum { get; set; }
        public string Reason { get; set; }
        public string BlockedAuthorizationStatus { get; set; }
        public Nullable<int> BlockedAuthorizer { get; set; }
        public Nullable<System.DateTime> AuthorizationDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Branch { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Shareholder Shareholder { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
