//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int CertID { get; set; }
        public int ShID { get; set; }
        public string PaymentIDs { get; set; }
        public string BeginingSerial { get; set; }
        public string EndingSerial { get; set; }
        public string CertNum { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> DeliveryStatus { get; set; }
        public string DeliveredBy { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string CertAuthorizationStatus { get; set; }
        public Nullable<System.DateTime> CertGenerationDate { get; set; }
        public Nullable<int> CertAuthorizer { get; set; }
        public string Remark { get; set; }
    
        public virtual Shareholder Shareholder { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
