//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dividend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dividend()
        {
            this.DividenedDetails = new HashSet<DividenedDetail>();
        }
    
        public int DivID { get; set; }
        public System.DateTime Year { get; set; }
        public decimal DivPerShare { get; set; }
        public decimal TaxableAmount { get; set; }
        public decimal TaxRate { get; set; }
        public Nullable<System.DateTime> RunningDate { get; set; }
        public Nullable<int> NumOutstandingDays { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DividenedDetail> DividenedDetails { get; set; }
    }
}
