//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dividend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dividend()
        {
            this.DividenedDetails = new HashSet<DividenedDetail>();
            this.SimulationDivideneds = new HashSet<SimulationDividened>();
        }
    
        public int DivID { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> TotalWASA { get; set; }
        public string FiscalYear { get; set; }
        public Nullable<decimal> DivPerShare { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<System.DateTime> RunningDate { get; set; }
        public Nullable<int> NumOutstandingDays { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string AuthorizationStatus { get; set; }
        public Nullable<int> Authorizer { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DividenedDetail> DividenedDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulationDividened> SimulationDivideneds { get; set; }
    }
}
