//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DividenedDetail
    {
        public int ID { get; set; }
        public int DivID { get; set; }
        public int ShID { get; set; }
        public int PayID { get; set; }
        public int SubID { get; set; }
        public decimal DividenedAmount { get; set; }
        public Nullable<decimal> TaxedDividened { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> Capitalization { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<int> RequestHandler { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<System.DateTime> DateApplication { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public System.DateTime DividenedYear { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual Branch Branch2 { get; set; }
        public virtual Dividend Dividend { get; set; }
        public virtual Shareholder Shareholder { get; set; }
        public virtual Payment Payment1 { get; set; }
        public virtual Subscribtion Subscribtion { get; set; }
        public virtual User User { get; set; }
    }
}
