//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocID { get; set; }
        public string DocName { get; set; }
        public string DocType { get; set; }
        public string DocPath { get; set; }
        public string DocOwner { get; set; }
        public Nullable<int> ShID { get; set; }
        public Nullable<int> ProxyID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string DocAuthorizationStatus { get; set; }
        public Nullable<int> DocAuthorizer { get; set; }
        public Nullable<System.DateTime> DocAuthorizationDate { get; set; }
    
        public virtual Proxy Proxy { get; set; }
        public virtual Shareholder Shareholder { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
