//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Migration_Errors
    {
        public int ErrorID { get; set; }
        public string ShareID { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
    }
}
