//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Shareholder_Management_SystemEntities1 : DbContext
    {
        public Shareholder_Management_SystemEntities1()
            : base("name=Shareholder_Management_SystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<Blocked> Blockeds { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Dividend> Dividends { get; set; }
        public virtual DbSet<DividenedDetail> DividenedDetails { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Proxy> Proxies { get; set; }
        public virtual DbSet<Shareholder> Shareholders { get; set; }
        public virtual DbSet<ShareTransfer> ShareTransfers { get; set; }
        public virtual DbSet<Subscribtion> Subscribtions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ShCategory> ShCategories { get; set; }
    }
}
