//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Blockeds = new HashSet<Blocked>();
            this.DividenedDetails = new HashSet<DividenedDetail>();
            this.Payment1 = new HashSet<Payment>();
            this.SimulationDivideneds = new HashSet<SimulationDividened>();
        }
    
        public int PayID { get; set; }
        public Nullable<int> ShID { get; set; }
        public Nullable<int> SubID { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string ReferenceNum { get; set; }
        public Nullable<int> PaymentSlip { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> PaymentTransferFrom { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string PaymentAuthorizationStatus { get; set; }
        public Nullable<int> PaymentAuthorizer { get; set; }
        public Nullable<System.DateTime> AuthorizationDate { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> BlockedAmount { get; set; }
        public Nullable<int> TransferedPayID { get; set; }
        public Nullable<int> TransferID { get; set; }
        public Nullable<decimal> TransferAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blocked> Blockeds { get; set; }
        public virtual Branch Branch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DividenedDetail> DividenedDetails { get; set; }
        public virtual Document Document { get; set; }
        public virtual Shareholder Shareholder { get; set; }
        public virtual Shareholder Shareholder1 { get; set; }
        public virtual ShareTransfer ShareTransfer { get; set; }
        public virtual Subscribtion Subscribtion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment1 { get; set; }
        public virtual Payment Payment2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimulationDividened> SimulationDivideneds { get; set; }
    }
}
