//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Staging
    {
        public Nullable<int> PayId { get; set; }
        public string ShareID { get; set; }
        public string ModeOfPayment { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string Reference { get; set; }
        public string SourceofFund { get; set; }
        public Nullable<int> PaymentSlip { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> TransferFrom { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string AuthorizationStatus { get; set; }
        public Nullable<int> Authorizer { get; set; }
        public Nullable<System.DateTime> Authorizationdate { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> BlockedAmount { get; set; }
        public Nullable<int> TranferedPayId { get; set; }
        public Nullable<int> TranferId { get; set; }
        public Nullable<decimal> TranferAmount { get; set; }
        public int TempID { get; set; }
    }
}
