//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        public Payment()
        {
            this.Blockeds = new HashSet<Blocked>();
            this.DividenedDetails = new HashSet<DividenedDetail>();
            this.ShareTransfers = new HashSet<ShareTransfer>();
        }

        public int PayID { get; set; }

        [Required]
        public int? ShID { get; set; }

        [Required]
        public int? SubID { get; set; }

        [Required]
        public string PaymentMode { get; set; }

        [Required]
        public int? Branch { get; set; }

        [Required]
        public decimal? PaidAmount { get; set; }

        [Required]
        public string ReferenceNum { get; set; }

        [Required]
        public DateTime? PaymentDate { get; set; }

        [Required]
        public string PaymentAuthorizationStatus { get; set; }

        [Required]
        public int? PaymentSlip { get; set; }
        public int? PaymentTransferFrom { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreationDate { get; set; }
        public int? PaymentAuthorizer { get; set; }
        public DateTime? AuthorizationDate { get; set; }
        public string Remark { get; set; }
        public decimal? BlockedAmount { get; set; }
        [Required]
        public string SourceOfFunds { get; set; }

        public virtual ICollection<Blocked> Blockeds { get; set; }
        public virtual Branch Branch1 { get; set; }
        public virtual ICollection<DividenedDetail> DividenedDetails { get; set; }
        public virtual Document Document { get; set; }
        public virtual Shareholder Shareholder { get; set; }
        public virtual Shareholder Shareholder1 { get; set; }
        public virtual Subscribtion Subscribtion { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ShareTransfer> ShareTransfers { get; set; }
    }
}

