//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int perm_id { get; set; }
        public string role_name { get; set; }
        public string perm_family { get; set; }
        public string perm_name { get; set; }
        public string perm_controller { get; set; }
        public string perm_action { get; set; }
    }
}
