//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proxy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proxy()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int ProxyID { get; set; }
        public int ShID { get; set; }
        public string FullName { get; set; }
        public string Nationality { get; set; }
        public string Region { get; set; }
        public string Zone { get; set; }
        public string City { get; set; }
        public string Subcity { get; set; }
        public string Woreda { get; set; }
        public string Kebele { get; set; }
        public string PhoneNo { get; set; }
        public string PhoneNo2 { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ProxyStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ProxyAuthorizationStatus { get; set; }
        public Nullable<int> ProxyAuthorizer { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ProxyDocument { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Shareholder Shareholder { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Document Document { get; set; }
    }
}
