//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareTransfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShareTransfer()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int TransferID { get; set; }
        public Nullable<int> TransferrorShID { get; set; }
        public Nullable<int> TransfareeShID { get; set; }
        public string TransferCategory { get; set; }
        public string TransferType { get; set; }
        public string SubID { get; set; }
        public string PayID { get; set; }
        public Nullable<int> NumSharesTransferred { get; set; }
        public Nullable<decimal> AmountPerShare { get; set; }
        public Nullable<decimal> PaidAmountForTransfer { get; set; }
        public string TransferReason { get; set; }
        public string DividenedFor { get; set; }
        public Nullable<int> TransferDoc { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string TransferAuthorizationStatus { get; set; }
        public Nullable<int> TransferAuthorizer { get; set; }
        public Nullable<System.DateTime> TransferAuthorizationDate { get; set; }
        public string Remark { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Shareholder Shareholder { get; set; }
        public virtual Shareholder Shareholder1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
