//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription_Staging
    {
        public string ShareID { get; set; }
        public Nullable<int> SubNumShares { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> SubAmount { get; set; }
        public Nullable<decimal> PaidSubscription { get; set; }
        public Nullable<decimal> UnpaidSubscription { get; set; }
        public Nullable<int> SubTransferFrom { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public string SubStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> SubDate { get; set; }
        public string SubAuthorizationStatus { get; set; }
        public Nullable<int> SubAuthorizer { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Branch { get; set; }
        public int TempID { get; set; }
    }
}
