//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shareholder_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribtion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscribtion()
        {
            this.DividenedDetails = new HashSet<DividenedDetail>();
            this.Payments = new HashSet<Payment>();
            this.ShareTransfers = new HashSet<ShareTransfer>();
        }
    
        public int SubID { get; set; }
        public Nullable<int> ShID { get; set; }
        public Nullable<int> SubNumShares { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> SubAmount { get; set; }
        public Nullable<int> PaidSubscription { get; set; }
        public Nullable<decimal> UnpaidSubscription { get; set; }
        public Nullable<int> SubTransferFrom { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public string SubStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> SubDate { get; set; }
        public string SubAuthorizationStatus { get; set; }
        public Nullable<int> SubAuthorizer { get; set; }
        public Nullable<System.DateTime> AuthorizedDate { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DividenedDetail> DividenedDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Shareholder Shareholder { get; set; }
        public virtual Shareholder Shareholder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareTransfer> ShareTransfers { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
